anchor:role-chapiter

== Role

Cette partie décrit le fonctionnement des roles.

=== Prerequis

Précision sur le nom des rôles et comment ils sont stocké

* `master` : grand et unique chef d'une ressource
* `officer` : Sous-chef
* `member` : member

Pour les `groupes` et les `guildes`, le fonctionnement est le même, la table contenant les membres décrit le role à l'interieur de celle-ci.
Pour les `alliances`, le role est décrit au niveau de la `guilde` mais c'est uniquement le `master` de la `guilde` qui peut se voir attributé ce rôle dans l' `alliance`.


=== FacadeRole

Une facade nommé `Role` permet de testé l'autorisation à un utilisateur d'une ressource donnée.
Le fonctionnement est simple, la fonctionne va simplement recherché le role de la personne pour la ressource donnée.

A noté qu'une action sans role prerequis autorise toutes personnes à l'appellé comme l'action `index` par exemple.

Voici le tableau de role nécessaire selon la ressource et l'action demandé.

[source,php,indent=0]
----
include::../app/Classes/Role.php[lines=8..31]
----

Si la ressource demandé n'existe pas dans le tableau, la facade retourne une erreur.


=== MiddlewareRole

Le middleware nommé `role` permet de vérifé le droit d'appelle d'une route selon cette liste de droit.
Le middleware utilise la facade `Role`.
