== Controller User

Cette partie décrit le fonctionnement du `controller` nommé `UsersController`

=== Route

Voici la liste concernant les routes utilisant ce `controller`

[source, php, indent=0]
----
include::../app/Http/routes.php[lines=35..37]

    [...]
include::../app/Http/routes.php[lines=44..47]

    [...]
include::../app/Http/routes.php[lines=87..93]
----


=== Profil

Ce `controller` est utilisé pour visionner son profile et l'éditer

==== Validation

Le formulaire reçu pour l'édition du profile est vérifé par `validator` une solution présente dans Laravel.
Il est nécessaire :
[source, php, indent=0]
----
include::../app/Http/Controllers/UsersController.php[lines=132..148]
----


=== Creation

Il est aussi utilisé pour la procédure d'inscription des utilisateurs sur le site.
L'inscription se passe en deux temps, une première phase classique qui crée un utilisateur selon les informations fournis par le formulaire.
Cette utilisateur n'est pas activé, il est nécessaire que l'utilisateur valide son compte via le mail envoyé à sa boite mail.

==== Validation

Le formulaire reçu est vérifé par `validator` une solution présente dans Laravel.
Il est nécessaire :
[source, php, indent=0]
----
include::../app/Http/Controllers/UsersController.php[lines=149..162]
----


==== Amélioration

===== Sécurité

Il n'y a actuellement aucun système sécurisant l'inscirption de robot sur le site.
Il est donc primordiale qu'en cas de mis en production du projet qu'un système sois mis en place.