== Controller Guilds

Cette partie décrit le fonctionnement du `controller` nommé `GuildsController`

=== Route

Voici la liste concernant les routes utilisant ce `controller`

[source, php, indent=0]
----
include::../../app/Http/routes.php[lines=59]

----
[source, php, indent=0]
----
include::../../app/Http/routes.php[lines=71..77]
----

=== Guild

Ce controller permet de visualiser les ressources de type `guildes` selon le `subdomain`.

==== ShowMy

Fonction permettant de tester si l'utilisateur possède une guilde sur le serveur. Si ce n'est pas le cas, on lui affiche une erreur.

[source, php, indent=0]
----
include::../../app/Http/Controllers/GuildsController.php[lines=77..84]
----

==== canCreate

Fonction permettant de tester si l'utilisateur possède une guilde sur le serveur. Si c'est le cas on lui affiche une erreur.
Cette fonction est réutilisée pour les fonctions `Index`, `Create` et `Store`

[source, php, indent=0]
----
include::../../app/Http/Controllers/GuildsController.php[lines=137..145]
----

=== Vue Guilds

Cette partie décrit les spécifités de certaines vues

==== show.blade.php

Affichage des détails de la guilde.

Affiche ou cache les bouttons permettant de `quitter`, `editer` ou `suprimmer` la guilde.
Nous testons le rôle de l'utilisateur (master ou officier) et si il possède déjà une guilde.

[source, php, indent=0]
----
include::../../resources/views/guilds/show.blade.php [lines=13..27]
----

Affiche ou cache le bouton permettant de retirer la guilde de l'alliance où elle se trouve.
Si la guilde est master de l'alliance et qu'elle souhaite se retirer elle ne pourra pas.

[source, php, indent=0]
----
include::../../resources/views/guilds/show.blade.php [lines=30..42]
----

=== Améliorations

L'implémentation de la gestion des membres n'a pas pu être faite.
Cette partie est un controller indépendant du controller des `guildes` mais intéragie avec les membres de celle-ci.
Les fonctionalités manquant étant :

    * La changement de role du membre
    * Le passage du role `master` à un autre membre
    * Le kick et ban d'un membre
    * Le unban d'un joueur banni
    * L'invitation de membre ou la demande d'intégration à la guilde par un joueur

Le système de rôle prevoit déjà une grande majorité de ces actions.
