== Route

Cette partie décrit le fonctionnement des routes présents dans `raidplanner`

[source, php]
----
include::../app/Http/routes.php[lines=25..97]
----

=== Découpage du site

Le site fonctionne en deux partie.

==== Partie public

La partie public qui regroupe les informations concernant la platforme.
Elle intégre l'authentification qui est unifié entre cette partie et la partie 'application'.
Depuis la partie public, il est possible de listé tous les serveurs où il est possible de naviguer.

==== Partie application

Pour accéder à cette partie, il est nécessaire de choisir un server (`subdomain`) décrit dans le chapitre xref:subdomain-chapitre[subdomain].
Cette partie regroupe la totalité des fonctionnalités de l'application.
Il est possible de modifié son profile qui est visionable avec les informations spécifiques au serveur comme ces `archétypes` (personnage).

=== Restful

Les ressources `guilds`, `alliances` et `groups` sont des routes purement `Restful`.
Les routes pour permettre l'édition des membres ont été rajouter.


Les `short link` permettent de simplifé les chemins pour accéder au ressource propre à l'utilisateur authentifié.

==== NestedResource

Des nestedResources sont présente dans le projet. Elle conciste à une action intéragisant avec deux ressources comme celle-ci :
[source, php]
----
include::../../app/Http/routes.php[lines=66]
----

C'est route sont nommées avec une séparation en `'.'` pour séparé les différentes ressources.

=== RouteParser

Une facade nommé `RouteParser` permet de parser les noms des routes pour permettre sont utilisation.
[source, php]
----
include::../../app/Classes/RouteParser.php[lines=8..32]
----

Les functions `nested` permet de séparé plus précisement `la sub-ressources` et `l'action` et de vérifié si la route est bien une `nestedResource`.

=== TempController

Le `TempController` est la pour l'ajout des routes pour des actions encore non implémenté.
Il retourne la valeur `false` à chaque function.